package au.com.optus.ngcemigrations;
import au.com.optus.dev1.datamodels.CE_Mobile_Migration_Service_Discovery;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PushUpdate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long pam_process_id;
	private java.lang.String task_name;
	private java.lang.String task_status;
	private java.lang.String error_msg;
	private java.lang.String config_diff;
	private CE_Mobile_Migration_Service_Discovery result;
	private java.lang.Long sub_process_instance_id;

	public PushUpdate() {
	}

	public java.lang.Long getPam_process_id() {
		return this.pam_process_id;
	}

	public void setPam_process_id(java.lang.Long pam_process_id) {
		this.pam_process_id = pam_process_id;
	}

	public java.lang.String getTask_name() {
		return this.task_name;
	}

	public void setTask_name(java.lang.String task_name) {
		this.task_name = task_name;
	}

	public java.lang.String getTask_status() {
		return this.task_status;
	}

	public void setTask_status(java.lang.String task_status) {
		this.task_status = task_status;
	}

	public java.lang.String getError_msg() {
		return this.error_msg;
	}

	public void setError_msg(java.lang.String error_msg) {
		this.error_msg = error_msg;
	}

	public java.lang.String getConfig_diff() {
		return this.config_diff;
	}

	public void setConfig_diff(java.lang.String config_diff) {
		this.config_diff = config_diff;
	}

	public au.com.optus.dev1.datamodels.CE_Mobile_Migration_Service_Discovery getResult() {
		return this.result;
	}

	public void setResult(
			au.com.optus.dev1.datamodels.CE_Mobile_Migration_Service_Discovery result) {
		this.result = result;
	}

	public java.lang.Long getSub_process_instance_id() {
		return this.sub_process_instance_id;
	}

	public void setSub_process_instance_id(
			java.lang.Long sub_process_instance_id) {
		this.sub_process_instance_id = sub_process_instance_id;
	}

	public PushUpdate(
			java.lang.Long pam_process_id,
			java.lang.String task_name,
			java.lang.String task_status,
			java.lang.String error_msg,
			java.lang.String config_diff,
			au.com.optus.dev1.datamodels.CE_Mobile_Migration_Service_Discovery result,
			java.lang.Long sub_process_instance_id) {
		this.pam_process_id = pam_process_id;
		this.task_name = task_name;
		this.task_status = task_status;
		this.error_msg = error_msg;
		this.config_diff = config_diff;
		this.result = result;
		this.sub_process_instance_id = sub_process_instance_id;
	}

}